project:
  type: website
  output-dir: _site

website:
  page-navigation: true
  title: "CSC413 - Fall 2024, UTM"
  description: "Homepage for CSC413 - Neural Networks and Deep Learning, Fall 2024, UTM."
  site-url: "https://utm-csc413.github.io/2024F-website/"

  repo-url: https://github.com/utm-csc413/2024F-website
  repo-actions: [edit, issue]

  open-graph: true

  twitter-card:
    card-style: "summary" 

  page-footer:
    right: "This page is built with ❤️, [Quarto](https://quarto.org/) and inspiration from [STA210](https://sta210-s22.github.io/website/)."
    left: "&copy; Copyright 2024, Florian Shkurti"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/network.jpg"
    pinned: true
    align: center
    title: "UTM - CSC413 Neural Networks and Deep Learning"
    
    tools:
      - icon: github
        href: https://github.com/utm-csc413 
        text: "Github workspace for the course"
      - icon: chat-quote
        href: https://q.utoronto.ca/courses/366713/external_tools/18207
        text: "Discuss on Piazza"
      - icon: megaphone
        href: https://q.utoronto.ca/courses/366713
        text: "Official announcements on Quercus"
      - icon: envelope-at
        href: course-team.html
        text: "Email teaching staff"
   	
        
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview
      - href: https://q.utoronto.ca/courses/366713/external_tools/18207
        text: Piazza
      - href: https://q.utoronto.ca/courses/366713
        text: Quercus	
      - href: course-syllabus.qmd
        text: Syllabus
      - href: course-team.qmd
        text: Teaching Staff
      - href: course-schedule.qmd
        text: Schedule
      # - href: weekly-material.qmd
      #   text: Weekly Material
      - section: "Weekly materials"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"
          - href: weeks/week-2.qmd
            text: "Week 2"
          - href: weeks/week-3.qmd
            text: "Week 3"
          - href: weeks/week-4.qmd
            text: "Week 4"
          - href: weeks/week-5.qmd
            text: "Week 5"
          - href: weeks/week-6.qmd
            text: "Week 6"
          - href: weeks/week-7.qmd
            text: "Week 7"
          - href: weeks/week-8.qmd
            text: "Week 8"
          - href: weeks/week-9.qmd
            text: "Week 9"
          - href: weeks/week-10.qmd
            text: "Week 10"
          - href: weeks/week-11.qmd
            text: "Week 11"
          - href: weeks/week-12.qmd
            text: "Week 12"
          - href: weeks/week-13.qmd
            text: "Week 13"
          - href: weeks/week-14.qmd
            text: "Week 14"
      - href: project-description.qmd
        text: Final Project
      
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    
freeze: auto

editor: visual